import PerunDBAL

/// PostgreSQL rendering policy.
public struct PostgresDialect: SQLDialect {
    /// PostgreSQL features used by the portable renderer and ORM.
    public let capabilities: DialectCapabilities = [
        .returning,
        .nativeBoolean,
        .nativeTimestamp,
        .nativeUUID,
    ]

    /// Creates a stateless PostgreSQL rendering policy.
    public init() {}

    /// Returns PostgreSQL's one-based `$n` placeholder.
    public func placeholder(at position: Int) -> String {
        precondition(position > 0, "placeholder positions are one-based")
        return "$\(position)"
    }

    public func renderColumnType(_ type: ColumnType) -> String {
        switch type {
        case .boolean: "BOOLEAN"
        case .int32: "INTEGER"
        case .int64: "BIGINT"
        case .double: "DOUBLE PRECISION"
        case .text: "TEXT"
        case .blob: "BYTEA"
        case .timestamp: "TIMESTAMPTZ"
        case .uuid: "UUID"
        }
    }

    public func renderGeneratedPrimaryKeyColumn(_ name: String) -> String {
        "\(quoteIdentifier(name)) BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    }

    public func paginationPlan(
        limit: Int,
        offset: Int?,
        context: SQLPaginationContext
    ) -> SQLPaginationPlan {
        var fragments: [SQLPaginationFragment] = [
            .literal("LIMIT "),
            .parameter(limit),
        ]
        if let offset {
            fragments.append(contentsOf: [
                .literal(" OFFSET "),
                .parameter(offset),
            ])
        }
        return SQLPaginationPlan(placement: .suffix, fragments: fragments)
    }

    public func insertReturningPlan(columns: [String]) -> SQLDMLReturningPlan? {
        returningPlan(columns: columns)
    }

    public func updateReturningPlan(columns: [String]) -> SQLDMLReturningPlan? {
        returningPlan(columns: columns)
    }

    public func deleteReturningPlan(columns: [String]) -> SQLDMLReturningPlan? {
        returningPlan(columns: columns)
    }

    private func returningPlan(columns: [String]) -> SQLDMLReturningPlan {
        var fragments: [SQLDMLReturningFragment] = [.literal("RETURNING ")]
        for (index, column) in columns.enumerated() {
            if index > 0 {
                fragments.append(.literal(", "))
            }
            fragments.append(.column(column))
        }
        return SQLDMLReturningPlan(placement: .suffix, fragments: fragments)
    }
}
