import PerunDBAL
import PerunDBALPostgres
import PerunDBALSQLite
import Testing

@Test
func createTableRendererUsesEachDialectsTypeVocabulary() throws {
    let createTable = SQLCreateTable(
        table: "type\"samples",
        columns: [
            SQLColumnDefinition(
                name: "id",
                type: .int64,
                role: .primaryKey(generated: false)
            ),
            SQLColumnDefinition(name: "flag", type: .boolean),
            SQLColumnDefinition(name: "small", type: .int32),
            SQLColumnDefinition(name: "large", type: .int64),
            SQLColumnDefinition(name: "score", type: .double, nullable: true),
            SQLColumnDefinition(name: "display\"name", type: .text, unique: true),
            SQLColumnDefinition(name: "payload", type: .blob, nullable: true),
            SQLColumnDefinition(name: "created_at", type: .timestamp),
            SQLColumnDefinition(name: "token", type: .uuid),
        ]
    )

    let postgres = try SQLRenderer(dialect: PostgresDialect()).render(createTable)
    #expect(
        postgres == RenderedSQL(
            sql: "CREATE TABLE \"type\"\"samples\" (\"id\" BIGINT NOT NULL PRIMARY KEY, \"flag\" BOOLEAN NOT NULL, \"small\" INTEGER NOT NULL, \"large\" BIGINT NOT NULL, \"score\" DOUBLE PRECISION, \"display\"\"name\" TEXT NOT NULL UNIQUE, \"payload\" BYTEA, \"created_at\" TIMESTAMPTZ NOT NULL, \"token\" UUID NOT NULL)",
            parameters: []
        )
    )

    let sqlite = try SQLRenderer(dialect: SQLiteDialect()).render(createTable)
    #expect(
        sqlite == RenderedSQL(
            sql: "CREATE TABLE \"type\"\"samples\" (\"id\" BIGINT NOT NULL PRIMARY KEY, \"flag\" BOOLEAN NOT NULL, \"small\" INT NOT NULL, \"large\" BIGINT NOT NULL, \"score\" REAL, \"display\"\"name\" TEXT NOT NULL UNIQUE, \"payload\" BLOB, \"created_at\" TEXT NOT NULL, \"token\" TEXT NOT NULL)",
            parameters: []
        )
    )
}

@Test
func createTableRendererDelegatesTheWholeGeneratedPrimaryKeyPhrase() throws {
    let createTable = SQLCreateTable(
        table: "generated_samples",
        columns: [
            SQLColumnDefinition(
                name: "id",
                type: .int64,
                role: .primaryKey(generated: true)
            ),
            SQLColumnDefinition(name: "token", type: .text, unique: true),
        ]
    )

    let postgres = try SQLRenderer(dialect: PostgresDialect()).render(createTable)
    #expect(
        postgres.sql == "CREATE TABLE \"generated_samples\" (\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"token\" TEXT NOT NULL UNIQUE)"
    )

    let sqlite = try SQLRenderer(dialect: SQLiteDialect()).render(createTable)
    #expect(
        sqlite.sql == "CREATE TABLE \"generated_samples\" (\"id\" INTEGER PRIMARY KEY, \"token\" TEXT NOT NULL UNIQUE)"
    )
    #expect(postgres.parameters.isEmpty)
    #expect(sqlite.parameters.isEmpty)
}

@Test
func createTableRendererUsesConditionalCreateSupportedByAdapters() throws {
    let createTable = SQLCreateTable(
        table: "migration_history",
        columns: [SQLColumnDefinition(name: "position", type: .int64)],
        ifNotExists: true
    )

    let postgres = try SQLRenderer(dialect: PostgresDialect()).render(createTable)
    #expect(
        postgres == RenderedSQL(
            sql: "CREATE TABLE IF NOT EXISTS \"migration_history\" (\"position\" BIGINT NOT NULL)",
            parameters: []
        )
    )

    let sqlite = try SQLRenderer(dialect: SQLiteDialect()).render(createTable)
    #expect(
        sqlite == RenderedSQL(
            sql: "CREATE TABLE IF NOT EXISTS \"migration_history\" (\"position\" BIGINT NOT NULL)",
            parameters: []
        )
    )
}

@Test
func createTableRendererUsesSourceCompatibleDefaultDialectHead() throws {
    let renderer = SQLRenderer(dialect: DefaultCreateTableDialect())
    let columns = [SQLColumnDefinition(name: "position", type: .int64)]

    let unconditional = try renderer.render(
        SQLCreateTable(table: "migration_history", columns: columns)
    )
    #expect(
        unconditional.sql == "CREATE TABLE \"migration_history\" (\"position\" BIGINT NOT NULL)"
    )

    #expect(throws: SQLDialectFeatureError.createTableIfNotExistsUnsupported) {
        try renderer.render(
            SQLCreateTable(
                table: "migration_history",
                columns: columns,
                ifNotExists: true
            )
        )
    }
}

@Test
func createTableInitializerReferenceRemainsSourceCompatible() {
    let makeCreateTable: (String, [SQLColumnDefinition]) -> SQLCreateTable =
        SQLCreateTable.init(table:columns:)

    let createTable = makeCreateTable(
        "migration_history",
        [SQLColumnDefinition(name: "position", type: .int64)]
    )

    #expect(createTable.table == "migration_history")
    #expect(createTable.columns.count == 1)
    #expect(!createTable.ifNotExists)
}

@Test
func createTableRendererRejectsStructurallyInvalidStatements() {
    let renderer = SQLRenderer(dialect: SQLiteDialect())
    let attribute = SQLColumnDefinition(name: "value", type: .text)

    #expect(throws: SQLRenderError.emptyTable) {
        try renderer.render(SQLCreateTable(table: "", columns: [attribute]))
    }
    #expect(throws: SQLRenderError.noTableColumns) {
        try renderer.render(SQLCreateTable(table: "samples", columns: []))
    }
    #expect(throws: SQLRenderError.emptyColumn) {
        try renderer.render(
            SQLCreateTable(
                table: "samples",
                columns: [SQLColumnDefinition(name: "", type: .text)]
            )
        )
    }
    #expect(throws: SQLRenderError.identifierContainsNullByte) {
        try renderer.render(
            SQLCreateTable(
                table: "samples",
                columns: [SQLColumnDefinition(name: "visible\0hidden", type: .text)]
            )
        )
    }
    #expect(throws: SQLRenderError.duplicateTableColumn("NAME")) {
        try renderer.render(
            SQLCreateTable(
                table: "samples",
                columns: [
                    SQLColumnDefinition(name: "name", type: .text),
                    SQLColumnDefinition(name: "NAME", type: .text),
                ]
            )
        )
    }
    #expect(throws: SQLRenderError.multiplePrimaryKeys) {
        try renderer.render(
            SQLCreateTable(
                table: "samples",
                columns: [
                    SQLColumnDefinition(
                        name: "first_id",
                        type: .int64,
                        role: .primaryKey(generated: false)
                    ),
                    SQLColumnDefinition(
                        name: "second_id",
                        type: .int64,
                        role: .primaryKey(generated: false)
                    ),
                ]
            )
        )
    }
    #expect(throws: SQLRenderError.nullablePrimaryKey("id")) {
        try renderer.render(
            SQLCreateTable(
                table: "samples",
                columns: [
                    SQLColumnDefinition(
                        name: "id",
                        type: .int64,
                        nullable: true,
                        role: .primaryKey(generated: false)
                    ),
                ]
            )
        )
    }
    #expect(
        throws: SQLRenderError.generatedPrimaryKeyRequiresInt64(
            column: "id",
            actual: .int32
        )
    ) {
        try renderer.render(
            SQLCreateTable(
                table: "samples",
                columns: [
                    SQLColumnDefinition(
                        name: "id",
                        type: .int32,
                        role: .primaryKey(generated: true)
                    ),
                ]
            )
        )
    }
}

private struct DefaultCreateTableDialect: SQLDialect {
    let capabilities: DialectCapabilities = []

    func placeholder(at position: Int) -> String { ":\(position)" }
}
